# Generated by Django 3.1.7 on 2021-04-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scheduleserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sername', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'scheduleserver',
            },
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'serverlist',
            },
        ),
    ]
