# Generated by Django 3.1.7 on 2021-04-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleserver',
            name='start',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scheduleserver',
            name='stop',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
