# Generated by Django 3.1.7 on 2021-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210420_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleserver',
            name='From',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleserver',
            name='To',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleserver',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
