# Generated by Django 3.1.7 on 2021-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210519_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleserver',
            name='start',
            field=models.TimeField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleserver',
            name='stop',
            field=models.TimeField(max_length=10, null=True),
        ),
    ]
