# Generated by Django 3.1.7 on 2021-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210520_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='rds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RDSname', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start', models.TimeField(max_length=10, null=True)),
                ('stop', models.TimeField(max_length=10, null=True)),
                ('From', models.DateField(blank=True, null=True)),
                ('To', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rds',
            },
        ),
    ]
