# Generated by Django 3.1.7 on 2021-08-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_rds'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleserver',
            name='scheduleFlag',
            field=models.IntegerField(default=0),
        ),
    ]
