# Generated by Django 3.1.7 on 2021-09-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schedule', '0006_scheduleserver_scheduleflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleserver',
            name='user_grp',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
