# Generated by Django 3.1.7 on 2021-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20210922_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetail',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
