# Generated by Django 3.1.7 on 2021-10-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_requestdetail_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='InstID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
